### ISSUE TITLE
Failed to activate the minimap package

### ISSUE THREAD

**Issue by juanse962** [olmokramer/atom-minimap-codeglance#20] opened 2015-11-08 03:19 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.4.4
### Stack Trace

Failed to activate the minimap package

```
At Cannot read property 'style' of undefined

TypeError: Cannot read property 'style' of undefined
  at minimap-codeglance.showLineNumbers (/Users/juangomez/.atom/packages/minimap-codeglance/lib/minimap-codeglance-element.js:79:20)
  at /Users/juangomez/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:32:28
  at Config.module.exports.Config.observeKeyPath (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Object.initialize (/Users/juangomez/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:31:66)
  at minimapCodeglance (/Users/juangomez/.atom/packages/minimap-codeglance/lib/minimap-codeglance.js:172:35)
  at Object.activatePlugin (/Users/juangomez/.atom/packages/minimap-codeglance/lib/main.js:52:69)
  at Main.module.exports.PluginManagement.updatesPluginActivationState (/Users/juangomez/.atom/packages/minimap/lib/mixins/plugin-management.coffee:89:14)
  at /Users/juangomez/.atom/packages/minimap/lib/mixins/plugin-management.coffee:110:8
  at Config.module.exports.Config.observeKeyPath (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/config.js:549:7)
  at Config.module.exports.Config.observe (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/config.js:129:21)
  at Main.module.exports.PluginManagement.registerPluginControls (/Users/juangomez/.atom/packages/minimap/lib/mixins/plugin-management.coffee:109:49)
  at Main.module.exports.PluginManagement.registerPlugin (/Users/juangomez/.atom/packages/minimap/lib/mixins/plugin-management.coffee:42:6)
  at Object.consumeMinimapServiceV1 (/Users/juangomez/.atom/packages/minimap-codeglance/lib/main.js:39:18)
  at Provider.module.exports.Provider.provide (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at ServiceHub.module.exports.ServiceHub.provide (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:392:65)
  at Package.module.exports.Package.activateNow (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:235:16)
  at /Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Users/juangomez/Documents/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -9:03.8.0 settings-view:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:12.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -7:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:18.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-gooey-syntax.theme-atom-material-ui)
 11x -1:10.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:06.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-gooey-syntax"
    ]
  },
  "minimap-codeglance": {}
}
```
### Installed Packages

``` coffee
# User
atom-gooey-syntax, v0.2.1
atom-material-ui, v0.7.1
emmet, v2.3.14
file-icons, v1.6.11
linter, vundefined
linter-xo, v0.8.0
minimap, v4.16.0
minimap-codeglance, v0.4.4
minimap-find-and-replace, v4.3.2

# Dev
No dev packages
```

**Comment by davisonio** [comment] 2017-03-29 20:38
This seems to be a duplicate of #18

**Closed as completed by davisonio** 2017-03-29 20:38 UTC
