### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getFirstVisibleScreenRow' of undefined

### ISSUE THREAD

**Issue by ObviouslyGreen** [olmokramer/atom-minimap-codeglance#6] opened 2015-07-20 19:10 UTC
Currently trying to reproduce, happened when I highlighted a line of text.

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [minimap-codeglance](https://github.com/olmokramer/atom-minimap-codeglance) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getFirstVisibleScreenRow' of undefined

```
At C:\Users\ASUser\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:142

TypeError: Cannot read property 'getFirstVisibleScreenRow' of undefined
  at Object.screenPositionForOffset (C:\Users\ASUser\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:142:45)
  at Object.scrollToMousePosition (C:\Users\ASUser\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:127:31)
  at atom-text-editor-minimap.<anonymous> (C:\Users\ASUser\.atom\packages\minimap-codeglance\lib\minimap-codeglance.js:51:21)

```
### Commands

```
     -0:18.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18 core:move-up (atom-text-editor.editor.is-focused)
     -0:17.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:17.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:17 core:move-down (atom-text-editor.editor.is-focused)
     -0:16 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:move-down (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "naturegreen-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-ui, v0.5.5
file-icons, v1.5.8
fonts, v0.5.0
minimap, v4.12.0
minimap-codeglance, v0.2.0
minimap-hide, v0.3.0
naturegreen-dark-syntax, v0.1.0
pigments, v0.8.4

# Dev
No dev packages
```

**Comment by olmokramer** [comment] 2015-07-21 11:17
Hi Shibo, Thanks for reporting the issue. I haven't been able to reproduce this, so could you tell me, was this while you were selecting the text, or after you had selected the text? Anyway, I've disabled codeglance during text selection as it was kind of annoying :) Please let me know if you've still got this issue after updating to v0.2.1. Thanks!

**Comment by ObviouslyGreen** [comment] 2015-07-21 17:55
I haven't been able to reproduce it as well =/. The only particular thing I remember was that it was a fairly long line (text wrapped), and I think it happened while I was selecting the text. I'll make sure to post if it ever does happen again.

**Comment by olmokramer** [comment] 2015-07-22 01:26
Ok, that's a good _and_ a bad thing... Means there's probably some race condition I don't know about.. I'll try to figure it out, but if you've got any clues... :)

BTW, can you remember if you've had Atom open for a long time or not?

**Comment by ObviouslyGreen** [comment] 2015-07-22 01:40
Yeah, I think I left Atom on overnight. How could that affect the extension?

**Comment by olmokramer** [comment] 2015-07-29 18:29
I'm sorry, but I can't remember why I thought that could be relevant. I'll close this issue because it doesn't seem to be a problem anymore, but feel free to reopen it if it happens again.

**Closed as completed by olmokramer** 2015-07-29 18:29 UTC
